packages:
  - 'packages/*'

# Catalog for dependency version management
# See: https://pnpm.io/catalogs
catalog:
  # Node.js types
  '@types/node': ^22.8.0

  # HTTP client
  axios: ^1.7.7

  # HTML parsing
  cheerio: ^1.0.0

  # CSV handling
  csv-stringify: ^6.5.1

  # CLI utilities
  commander: ^12.1.0

  # Date handling (for future calendar tool)
  date-fns: ^4.1.0

  # Development dependencies
  typescript: ~5.6.3
  tsx: ^4.19.0

  # ESLint and plugins
  eslint: ^9.13.0
  typescript-eslint: ^8.12.2
  '@eslint/js': ^9.13.0
  globals: ^15.11.0

  # Testing (for future use)
  vitest: ^2.1.4
  '@vitest/ui': ^2.1.4

# Ensure packages have been available for at least 1 day before installing
# See: https://pnpm.io/settings#minimum-release-age (value in seconds: 1 day = 86400 seconds)
minimumReleaseAge: 86400
